
name: .NET Core Desktop

on:
  push:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  


    env:
      Solution_Name: CodeSwine-Solo_Public_Lobby/CodeSwine-Private_Public_Lobby.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build the application
      run: msbuild $env:Solution_Name /t:Build /p:Configuration=$env:Configuration /p:OutputPath=bin\${{ matrix.configuration }}
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Zip files
      #if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd CodeSwine-Solo_Public_Lobby/CodeSwine-Solo_Public_Lobby/bin/
        copy ${{ matrix.configuration }}/ CodeSwine-Solo_Public_Lobby/
        dir
        tar.exe -a -c -f CodeSwine-Solo_Public_Lobby.zip CodeSwine-Solo_Public_Lobby/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CodeSwine-Solo_Public_Lobby
        path: CodeSwine-Solo_Public_Lobby/CodeSwine-Solo_Public_Lobby/bin/${{ matrix.configuration }}

    - name: release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: CodeSwine-Solo_Public_Lobby.zip
    
